version: '3.1'

services:

  dc_web:
    image: nginx
    volumes:
      - ./code:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - dc_fpm
      - dc_postgres
    restart: always

  dc_fpm:
    build: .
    volumes:
        - ./code:/var/www/html
    restart: always    

  dc_postgres:
    image: postgres
    env_file: ./.env  
    restart: always
